# Generated by Django 6.0.3 on 2026-04-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('hobby', models.TextField()),
                ('favorite_subject', models.CharField(max_length=100)),
                ('about_me', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
